# Generated by Django 5.1 on 2024-08-26 14:47

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0002_rename_observacines_resoluciones_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='resoluciones',
            name='link_resolucion',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resoluciones',
            name='tsbuscar',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
       
    ]
