# Generated by Django 5.1 on 2024-08-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0003_resoluciones_link_resolucion_resoluciones_tsbuscar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resoluciones',
            name='tsbuscar',
        ),
    ]
