# Generated by Django 5.1 on 2024-08-26 17:17

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0004_remove_resoluciones_tsbuscar'),
    ]

    operations = [
        migrations.AddField(
            model_name='resoluciones',
            name='tsbuscar',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        # migrations.RunSQL(
        #     sql='''
        #       ALTER TABLE resoluciones ADD COLUMN tsbuscar tsvector GENERATED ALWAYS AS (
        #         setweight(to_tsvector('spanish', coalesce(numero, '')), 'A') ||
        #         setweight(to_tsvector('spanish', coalesce(sumario,'')), 'B') ||
        #         setweight(to_tsvector('spanish', coalesce(observaciones,'')), 'B')
        #       ) STORED;
        #     ''',
# 
        #     reverse_sql = '''
        #       ALTER TABLE film DROP COLUMN tsbuscar;
        #     '''
        # ),


        
    ]
